# Dockerfile.build
ARG PYTHON_VERSION=3.12
FROM python:${PYTHON_VERSION}-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app


RUN apt-get update \
 && apt-get install -y --no-install-recommends git \
 && rm -rf /var/lib/apt/lists/*


COPY pyproject.toml README.md LICENSE* /app/

RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir "flit_core>=3,<4"


COPY . /app


RUN pip install --no-cache-dir -e ".[dev]"

